@extends('biblioteca.layout')
@section('library')
<div class="bib-page-heading"><div><h2>{{ $control?'Control documental':($manage?'Administración de la biblioteca':($kind?$collections[$kind]['label']:'Buscar en la biblioteca')) }}</h2><p>{{ $control?'Versiones, estados y fechas de revisión de todas las colecciones.':($manage?'Creá documentos, revisá borradores y administrá sus publicaciones.':'Explorá los documentos y consultá su versión disponible.') }}</p></div>
@if($canManage)<div class="bib-actions"><a class="btn btn-outline-secondary" href="{{ route('biblioteca.visibility') }}">Aprobaciones y visibilidad</a><a class="btn btn-outline-secondary" href="{{ route('biblioteca.sync') }}">Sincronizar fuentes</a><a class="btn btn-outline-primary" href="{{ route('biblioteca.upload') }}">Importar descriptivo</a><a class="btn btn-primary" href="{{ route('biblioteca.new',['kind'=>$kind?:'descriptivos']) }}">+ Nuevo documento</a></div>@endif</div>
<details class="bib-section bib-details" open><summary>Buscador y filtros</summary><div class="bib-reading"><form method="get" class="bib-filters">
<div><label for="q">Buscar</label><input class="form-control" id="q" name="q" value="{{ $filters['q']??'' }}" placeholder="Nombre, tema o contenido"></div>
@if(!$kind)<div><label for="kind">Colección</label><select name="kind" id="kind" class="form-select"><option value="">Todas</option>@foreach($collections as $key=>$c)@continue(!$canManage && !app(\App\Services\Biblioteca\Governance::class)->sectionVisible($key))<option value="{{ $key }}" @selected(($filters['kind']??'')===$key)>{{ $c['label'] }}</option>@endforeach</select></div>@endif
<div><label for="area">Área / responsable</label><select name="area" id="area" class="form-select"><option value="">Todas</option>@foreach($areas as $a)<option @selected(($filters['area']??'')===$a)>{{ $a }}</option>@endforeach</select></div>
<div><label for="state">Estado</label><select name="state" id="state" class="form-select"><option value="">Todos</option>@foreach($states as $s)<option @selected(($filters['state']??'')===$s)>{{ $s }}</option>@endforeach</select></div>
<div><label for="review">Revisión</label><select name="review" id="review" class="form-select"><option value="">Todas</option>@foreach(['Pendiente','En revisión','Validado'] as $s)<option @selected(($filters['review']??'')===$s)>{{ $s }}</option>@endforeach</select></div>
<button class="btn btn-primary align-self-end">Aplicar</button>
@if(!$control)<label class="bib-check"><input type="checkbox" name="history" value="1" @checked($filters['history']??false)> Incluir retirados</label>@endif
</form></div></details>
<p class="bib-result-count">{{ $entries->total() }} {{ $control?'versiones':'documentos' }}</p>
<div class="bib-table-wrap"><table class="table bib-table"><thead><tr><th>Documento</th><th>Área / responsable</th><th>Versión y estado</th><th>{{ $control?'Próxima revisión':'Revisión' }}</th><th><span class="visually-hidden">Acciones</span></th></tr></thead><tbody>
@forelse($entries as $e)<tr><td><span class="bib-type" style="color:{{ $collections[$e['document']['kind']]['color'] }}">{{ $collections[$e['document']['kind']]['label'] }} {{ $e['document']['code']?'· '.$e['document']['code']:'' }}</span><a class="bib-document-link" href="{{ route('biblioteca.show',['document'=>$e['document']['id'],'version'=>$control?$e['version']['id']:null]) }}">{{ $e['title'] }}</a></td><td>{{ $e['area']?:'Sin registrar' }}</td><td><span class="bib-badge {{ $e['version']['current_slot']?'current':'' }}">{{ $e['state'] }}</span><small class="d-block mt-1">Versión interna {{ $e['version']['number'] }}</small></td><td>{{ $control?($e['nextReview']?:'Sin fecha programada'):$e['version']['review_state'] }}@if($e['situation'])<small class="d-block text-warning-emphasis">{{ $e['situation'] }}</small>@endif</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('biblioteca.show',['document'=>$e['document']['id'],'version'=>$control?$e['version']['id']:null]) }}">Abrir</a></td></tr>
@empty<tr><td colspan="5" class="p-5 text-center">No hay documentos que coincidan con estos filtros.</td></tr>@endforelse
</tbody></table></div>
@if($entries->hasPages())<nav class="bib-pagination" aria-label="Páginas de resultados">@if(!$entries->onFirstPage())<a class="btn btn-outline-primary" href="{{ $entries->previousPageUrl() }}">Anterior</a>@endif<span>Página {{ $entries->currentPage() }} de {{ $entries->lastPage() }}</span>@if($entries->hasMorePages())<a class="btn btn-outline-primary" href="{{ $entries->nextPageUrl() }}">Siguiente</a>@endif</nav>@endif
@endsection
