@extends('biblioteca.layout')
@section('library')
<div class="bib-page-heading"><div><h2>Revisar descriptivo</h2><p>{{ $entry['title'] }} · Versión {{ $entry['version']['number'] }}</p></div><a class="btn btn-outline-primary" href="{{ route('biblioteca.show',['document'=>$entry['document']['id'],'version'=>$entry['version']['id']]) }}">Consultar contenido</a></div>
<div class="bib-callout"><div><strong>1. Confirmá nombre y área. 2. Revisá el contenido. 3. Elegí la acción.</strong><p>Guardar conserva el avance. Validar confirma la revisión. Validar y publicar convierte esta versión en vigente y conserva la anterior en el historial.</p></div></div>
<form id="bib-review" data-url="{{ route('biblioteca.review.save',$entry['version']['id']) }}">
@csrf<input type="hidden" name="revision" value="{{ $entry['version']['revision'] }}"><input type="hidden" name="documentRevision" value="{{ $entry['document']['revision'] }}">
<section class="bib-section"><h3>Identificación</h3><div class="bib-form-grid bib-reading"><div><label for="canonical_name">Nombre del puesto</label><input id="canonical_name" name="canonical_name" class="form-control" maxlength="500" value="{{ $entry['document']['canonical_name']?:$entry['title'] }}"></div><div><label for="normalized_area">Área normalizada</label><input id="normalized_area" name="normalized_area" class="form-control" maxlength="500" value="{{ $entry['document']['normalized_area']?:$entry['area'] }}"></div><div><label for="aliases">Otros nombres confirmados <small>(uno por línea)</small></label><textarea class="form-control" name="aliases" id="aliases">{{ implode("\n",\App\Services\Biblioteca\Content::decode($entry['document']['aliases'])) }}</textarea></div><div><label for="observation">Observaciones pendientes</label><textarea class="form-control" name="observation" id="observation">{{ $entry['document']['observation'] }}</textarea></div></div></section>
<section class="bib-section"><h3>Comentario de la decisión</h3><div class="bib-reading"><label for="comment">Comentario opcional</label><textarea id="comment" name="comment" class="form-control" maxlength="4000" placeholder="Podés explicar qué verificaste o qué queda pendiente."></textarea><small>Al validar, el sistema registra automáticamente la decisión, tu usuario y la fecha.</small></div></section>
@if($findings->count())<section class="bib-section"><h3>Hallazgos de esta lectura</h3><div class="bib-reading">@foreach($findings as $f)@php($finding=\App\Services\Biblioteca\Content::decode($f->payload_json))<p><strong>{{ $finding['title'] }}</strong> · {{ $f->status }}<br>{{ $finding['detail'] }}</p>@endforeach</div></section>@endif
<div class="bib-actions"><button type="submit" class="btn btn-outline-primary" value="save">Guardar avance</button><button type="submit" class="btn btn-primary" value="validate">Validar revisión</button><button type="submit" class="btn btn-success" value="publish">Validar y publicar</button></div>
</form>
@endsection
