@extends('biblioteca.layout')
@section('library')
<a class="bib-back" href="{{ route('biblioteca.catalog',$entry['document']['kind']) }}">← {{ $collections[$entry['document']['kind']]['label'] }}</a>
<div class="bib-page-heading"><div><span class="bib-eyebrow">{{ $entry['document']['code']?:'DESCRIPTIVO DE PUESTO' }}</span><h2>{{ $entry['title'] }}</h2><p><span class="bib-badge {{ $entry['version']['current_slot']?'current':'' }}">{{ $entry['state'] }}</span> · Versión interna {{ $entry['version']['number'] }} · {{ $entry['version']['review_state'] }}</p></div><div class="bib-actions"><a class="btn btn-outline-secondary" href="{{ route('biblioteca.export',[$entry['version']['id'],'pdf']) }}">PDF</a><a class="btn btn-outline-secondary" href="{{ route('biblioteca.export',[$entry['version']['id'],'docx']) }}">Word</a><button class="btn btn-outline-secondary" type="button" data-bib-print>Imprimir</button></div></div>
@if($entry['situation'])<div class="alert alert-warning">{{ $entry['situation'] }}</div>@endif
@if($entry['version']['state']==='Borrador')<div class="alert alert-info">Este es un borrador. Guardarlo no reemplaza la versión publicada.</div>@endif
@if($canManage)<div class="bib-actions bib-management-bar" data-version="{{ $entry['version']['id'] }}" data-revision="{{ $entry['version']['revision'] }}" data-url="{{ route('biblioteca.action',$entry['version']['id']) }}">
@if($entry['version']['state']==='Borrador'&&!$entry['version']['published_at'])<a class="btn btn-primary" href="{{ route('biblioteca.edit',$entry['version']['id']) }}">Editar borrador</a><button class="btn btn-success" data-bib-action="publish">Publicar versión</button>@else<button class="btn btn-primary" data-bib-action="draft">Crear borrador para editar</button>@endif
@if($entry['job'])<a class="btn btn-outline-primary" href="{{ route('biblioteca.review',$entry['version']['id']) }}">Revisar descriptivo</a>@endif
<a class="btn btn-outline-secondary" href="{{ route('biblioteca.new',['kind'=>$entry['document']['kind'],'duplicate'=>$entry['version']['id']]) }}">Duplicar</a>
@if($entry['version']['state']!=='Histórico / retirado')<button class="btn btn-outline-danger ms-auto" data-bib-action="retire">Retirar versión</button>@endif
</div>@endif
@include('biblioteca.reading')
@if($findings->count())<details class="bib-section bib-details"><summary>Hallazgos de esta lectura ({{ $findings->count() }})</summary><div class="bib-reading">@foreach($findings as $f)@php($finding=\App\Services\Biblioteca\Content::decode($f->payload_json))<div class="bib-finding"><strong>{{ $finding['title'] }}</strong><span class="bib-badge ms-2">{{ $f->status }}</span><p>{{ $finding['detail'] }}</p>@if($f->resolution)<small>{{ $f->resolution }}</small>@endif</div>@endforeach</div></details>@endif
<details class="bib-section bib-details"><summary>Versiones e historial ({{ count($history) }})</summary><div class="bib-reading"><div class="bib-table-wrap"><table class="table"><thead><tr><th>Versión</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>@foreach($history as $v)<tr><td>{{ $v['number'] }}</td><td>{{ $v['state'] }}</td><td>{{ substr($v['published_at']?:$v['created_at'],0,10) }}</td><td><a href="{{ route('biblioteca.show',['document'=>$entry['document']['id'],'version'=>$v['id']]) }}">Consultar</a></td></tr>@endforeach</tbody></table></div>
@if(!$entry['job']&&!empty($entry['content']['history']))<h4>Antecedentes declarados en el documento</h4><ul>@foreach($entry['content']['history'] as $h)<li>{{ $h['version'] }} · {{ $h['date']?:'Sin fecha' }} · {{ $h['detail'] }}</li>@endforeach</ul>@endif</div></details>
@if($sources->count())<details class="bib-section bib-details"><summary>Documentos fuente y extracción ({{ $sources->count() }})</summary><div class="bib-reading">@foreach($sources as $s)<div class="bib-source"><div><strong>{{ $s->name }}</strong><small class="d-block">{{ $s->format }} · {{ $s->read_state }}</small></div><div class="bib-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('biblioteca.source',$s->id) }}">Ver fuente</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('biblioteca.source.file',$s->id) }}">Descargar original</a></div></div>@endforeach</div></details>@endif
@if($canManage)<details class="bib-section bib-details"><summary>Registro de acciones ({{ count($events) }})</summary><div class="bib-reading bib-event-list">@forelse($events as $event)<details class="bib-event"><summary>{{ substr($event['happened_at'],0,19) }} · {{ str_replace('_',' ',$event['action']) }} · {{ $event['actor'] }}</summary><div class="bib-event-data"><strong>Antes</strong><pre>{{ json_encode(\App\Services\Biblioteca\Content::decode($event['before_json']), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><strong>Después</strong><pre>{{ json_encode(\App\Services\Biblioteca\Content::decode($event['after_json']), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></div></details>@empty<p>Sin acciones registradas.</p>@endforelse</div></details>@endif
@endsection
